Update build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -28,21 +28,21 @@ if [ "$MKISOFS" = "" ]; then
    MKISOFS=$(which genisoimage)
 fi
 if [ "$MKISOFS" = "" ]; then
-   echo "Cannot find mkisofs or genisoimage, stop"
+   echo "mkisofs or genisoimage not found... You can install in sudo apt."
    exit 3
 fi
 
 # build initramfs image
 if [ "$SKIPINITRFS" = "" ]; then
-   echo "Building initramfs image..."
+   echo "Creating initramfs image..."
    cd initramfs
    INITRAMFS=$(./initramfs_create)
    cd ..
 fi
 
 # create live kit filesystem (cpio archive)
-rm -Rf "$LIVEKITDATA"
-BOOT="$LIVEKITDATA"/"$LIVEKITNAME"/boot
+rm -Rf "$DISTRODATA"
+BOOT="$DISTRODATA"/"$DISTRONAME"/boot
 mkdir -p "$BOOT"
 mkdir -p "$BOOT"/../changes
 mkdir -p "$BOOT"/../modules
@@ -53,8 +53,8 @@ fi
 
 # BIOS / MBR booting
 cp -r bootfiles/* $BOOT
-cat bootfiles/syslinux.cfg | sed -r "s:/boot/:/$LIVEKITNAME/boot/:" > $BOOT/syslinux.cfg
-cat bootfiles/bootinst.bat | sed -r "s:/boot/:/$LIVEKITNAME/boot/:" | sed -r "s:\\\\boot\\\\:\\\\$LIVEKITNAME\\\\boot\\\\:" > $BOOT/bootinst.bat
+cat bootfiles/syslinux.cfg | sed -r "s:/boot/:/$DISTRONAME/boot/:" > $BOOT/syslinux.cfg
+cat bootfiles/bootinst.bat | sed -r "s:/boot/:/$DISTRONAME/boot/:" | sed -r "s:\\\\boot\\\\:\\\\$LIVEKITNAME\\\\boot\\\\:" > $BOOT/bootinst.bat
 cp $VMLINUZ $BOOT/ || exit
 
 # UEFI booting
@@ -71,14 +71,13 @@ for i in $MKMOD; do
    fi
 done
 if [ "$SKIPCOREMOD" = "" ]; then
-   mksquashfs $COREFS $LIVEKITDATA/$LIVEKITNAME/01-core.$BEXT -comp xz -b 1024K -Xbcj x86 -always-use-fragments -keep-as-directory || exit
+   mksquashfs $COREFS $DISTRODATA/$DISTRONAME/01-core.$BEXT -comp xz -b 1024K -Xbcj x86 -always-use-fragments -keep-as-directory || exit
 fi
 
-cd "$LIVEKITDATA"
-ARCH=$(uname -m)
+cd "$DISTRODATA"
 TARGET=/tmp
 
-cat "$CWD/bootinfo.txt" | fgrep -v "#" | sed -r "s/mylinux/$LIVEKITNAME/" | sed -r "s/\$/\x0D/" > readme.txt
+cat "$CWD/bootinfo.txt" | fgrep -v "#" | sed -r "s/linuxseed/$DISTRONAME/" | sed -r "s/\$/\x0D/" > readme.txt
 
 echo cd $LIVEKITDATA '&&' $MKISOFS -o "$TARGET/$LIVEKITNAME-22.11-desktop-$ARCH.iso" -v -J -R -D -A "$LIVEKITNAME" -V "$LIVEKITNAME" \
 -no-emul-boot -boot-info-table -boot-load-size 4 \
